DROP TABLE IF EXISTS LendingBooks;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Readers;
DROP TABLE IF EXISTS Authors;
DROP TABLE IF EXISTS Publishers;




CREATE TABLE Authors
(
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    name NVARCHAR(256) NOT NULL
);

CREATE TABLE Publishers
(
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    name NVARCHAR(50) NOT NULL
);

CREATE TABLE Readers
(
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    name NVARCHAR(256) NOT NULL,
    registrationDate DATE NOT NULL,
);

CREATE TABLE Books
(
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    name NVARCHAR(50) NOT NULL,
    isbn VARCHAR(30),
    publishYear INT,
    count INT,
    publisherId UNIQUEIDENTIFIER NOT NULL REFERENCES Publishers (id),
    authorId UNIQUEIDENTIFIER NOT NULL REFERENCES Authors (id)
);

CREATE TABLE LendingBooks
(
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    readerId UNIQUEIDENTIFIER REFERENCES Readers (id),
    bookId UNIQUEIDENTIFIER REFERENCES Books (id),
    limitDate DATE,
    returned BIT
);